# Generated by Django 3.0.14 on 2026-07-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('rack_number', models.CharField(max_length=30)),
            ],
        ),
    ]
